# Site settings
title: TerminusDB Community
email:
description: > # this means to ignore newlines until "baseurl:"
  This is a community for people who are interested in learning about open source model driven graph databases.
#baseurl: "/terminusdb-community" # the subpath of your site, e.g. /blog/
url: "https://community.terminusdb.com" # the base hostname & protocol for your site
twitter_username: TerminusDB
github_username: terminusdb

# Build settings
include: ['_pages']
sass:
  sass_dir: _sass
kramdown:
  input: GFM
exclude:
  - Gemfile
  - Gemfile.lock
  - static/images/sources/
  - _pages/02_get_started.html
  - DOCS/
future: true
timezone: Europe/London

collections:
  sponsors:
    output: false
  chapters:
    output: true
  projects:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
  -
    scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
      is_chapter: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# command to run build locally:
# bundle exec jekyll serve --host 0.0.0.0 --config _config.yml,_config_dev.yml
